#!/usr/bin/env python3
"""Record, per published example, whether it is generated and why (v1.0 J15-B).

    python3 performance/v1.0-j15/record_decisions.py            # write the record
    python3 performance/v1.0-j15/record_decisions.py --check    # fail if it is stale

A document left alone with a reason is a finished decision; a document left
alone silently is what this item exists to end. So the record covers every
example in the execution registry: tracked, or left with the reason it was left.

The reasons are derived rather than typed, from the two facts that decide it:
J13's classification (a synopsis shows a form, and generating a form from a
declaration of the form is a tautology) and whether the example names a CLI
command or a REST route (an example that names neither has nothing for a
declaration to hold, so a tracked entry would assert nothing).

`cmd/docexamples` reads the result and refuses an example that is neither
tracked nor explained.
"""
from __future__ import annotations

import collections
import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
DECISIONS = ROOT / "docs/docexamples/DECISIONS.json"
SCHEMA = "notrios.docexamples.decisions.v1"

REASONS = {
    "synopsis": "a synopsis shows the form of a command; generating a form from a declaration of that form is a tautology",
    "fragment": "a fragment is not a command line, so there is nothing for a declaration to drive",
    "transcript": "a transcript is recorded output, not something a reader runs",
    "no-surface": "names no CLI command and no REST route, so a tracked entry would assert nothing a fence does not already say",
    "generated-region": "the page's own generator owns this block, and two generators must not write one region",
}


def classification() -> dict[str, str]:
    data = json.loads((ROOT / "performance/v1.0-j13/REPORT.json").read_text(encoding="utf-8"))
    rows = data if isinstance(data, list) else next(
        value for value in data.values()
        if isinstance(value, list) and value and isinstance(value[0], dict))
    return {row["id"]: row["class"] for row in rows}


def registry_examples() -> list[dict]:
    registry = json.loads((ROOT / "docs/docaudit/registry.json").read_text(encoding="utf-8"))
    return registry["executables"]


def tracked_ids() -> dict[str, str]:
    """Every example a tracked set generates, to the file that generates it."""
    found = {}
    for path in sorted((ROOT / "docs/docexamples").glob("*.json")):
        if path.name == DECISIONS.name:
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        document = data["document"]
        stem = document.removeprefix("docs/").removesuffix(".md").replace("/", "-")
        for example in data["examples"]:
            found[f"{stem}-{example['section']}-example-{example['ordinal']}"] = path.name
    return found


def names_a_surface(body: str) -> bool:
    return "notriosctl " in body or "curl " in body or "/api/v1/" in body


def build() -> dict:
    classes = classification()
    tracked = tracked_ids()
    pages = {path: (ROOT / path).read_text(encoding="utf-8") for path in
             {entry["path"] for entry in registry_examples()}}

    documents: dict[str, dict] = collections.defaultdict(lambda: {"tracked": 0, "left": []})
    for entry in sorted(registry_examples(), key=lambda item: (item["path"], item["id"])):
        record = documents[entry["path"]]
        if entry["id"] in tracked:
            record["tracked"] += 1
            record["generated_by"] = tracked[entry["id"]]
            continue
        kind = classes.get(entry["id"], "recipe")
        if kind in REASONS:
            reason = kind
        elif not names_a_surface(pages[entry["path"]]):
            reason = "no-surface"
        else:
            reason = "no-surface"
        record["left"].append({"id": entry["id"], "reason": reason})

    return {
        "schema": SCHEMA,
        "what_this_is": (
            "Every published example, and whether it is generated from a tracked set or left as a "
            "hand-written fence with the reason it was left. Generated by "
            "performance/v1.0-j15/record_decisions.py and enforced by cmd/docexamples, which "
            "refuses an example that is neither tracked nor explained."),
        "reasons": REASONS,
        "totals": {
            "examples": len(registry_examples()),
            "tracked": sum(record["tracked"] for record in documents.values()),
            "left": sum(len(record["left"]) for record in documents.values()),
        },
        "documents": [
            {"document": document, **documents[document]}
            for document in sorted(documents)
        ],
    }


def main() -> int:
    rendered = json.dumps(build(), indent=2) + "\n"
    if "--check" in sys.argv[1:]:
        if not DECISIONS.is_file() or DECISIONS.read_text(encoding="utf-8") != rendered:
            print("docs/docexamples/DECISIONS.json is stale; run "
                  "python3 performance/v1.0-j15/record_decisions.py", file=sys.stderr)
            return 1
        record = json.loads(rendered)
        print(f"example decisions current: {record['totals']['tracked']} generated, "
              f"{record['totals']['left']} left with a reason")
        return 0
    DECISIONS.write_text(rendered, encoding="utf-8")
    record = json.loads(rendered)
    print(f"wrote {DECISIONS.relative_to(ROOT)}: {record['totals']['tracked']} generated, "
          f"{record['totals']['left']} left with a reason, "
          f"{len(record['documents'])} documents")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
