// Package recoll drives the optional Recoll search sidecar. Recoll and Xapian
// are GPL, so this package only ever invokes user-installed binaries
// (recollindex/recollq) as external processes — nothing is linked, vendored,
// or redistributed (see RECOLL_INTEGRATION.md). When the binaries are absent,
// the service degrades gracefully to SQLite FTS5 search.
package recoll

import (
	"bytes"
	"context"
	"encoding/base64"
	_ "embed"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/renesugar/notrios/internal/query"
)

//go:embed notrios_md_handler.py
var handlerScript []byte

// Sidecar manages one Recoll configuration directory indexing one projection
// directory.
type Sidecar struct {
	ConfDir       string
	ProjectionDir string
	IndexBinary   string // recollindex
	QueryBinary   string // recollq
}

// New prepares a sidecar rooted at confDir. indexBinary defaults to
// "recollindex"; the matching recollq is derived from its directory.
func New(confDir, projectionDir, indexBinary string) *Sidecar {
	indexBinary = strings.TrimSpace(indexBinary)
	if indexBinary == "" {
		indexBinary = "recollindex"
	}
	queryBinary := "recollq"
	if dir := filepath.Dir(indexBinary); dir != "." {
		queryBinary = filepath.Join(dir, "recollq")
	}
	return &Sidecar{ConfDir: confDir, ProjectionDir: projectionDir, IndexBinary: indexBinary, QueryBinary: queryBinary}
}

// Available reports whether the Recoll binaries can be found.
func (s *Sidecar) Available() bool {
	if _, err := exec.LookPath(s.IndexBinary); err != nil {
		return false
	}
	_, err := exec.LookPath(s.QueryBinary)
	return err == nil
}

// EnsureConfig writes the generated Recoll configuration: recoll.conf watching
// the projection directory, the fields file declaring the Notrios prefixes and
// the publishedts integer range slot, mimeconf wiring text/markdown to the
// from-scratch front-matter handler, and the handler script itself.
func (s *Sidecar) EnsureConfig() error {
	if err := os.MkdirAll(s.ConfDir, 0o755); err != nil {
		return err
	}
	handlerPath := filepath.Join(s.ConfDir, "notrios_md_handler.py")
	if err := os.WriteFile(handlerPath, handlerScript, 0o755); err != nil {
		return err
	}
	recollConf := fmt.Sprintf(`# Generated by notriosd; edits are overwritten on startup.
topdirs = %s
loglevel = 2
# Underscores stay word characters so canonical identifiers survive intact.
underscoreasletter = 1
`, s.ProjectionDir)
	if err := os.WriteFile(filepath.Join(s.ConfDir, "recoll.conf"), []byte(recollConf), 0o644); err != nil {
		return err
	}
	fields := `# Generated by notriosd. Prefixes must be ASCII uppercase.
[prefixes]
tag = XTAG
alias = XALIAS
authorid = XAUTHORID
noteid = XNOTEID
threadid = XTHREADID
replyto = XREPLYTO
notebook = XNOTEBOOK
sourceurl = XSOURCEURL

[values]
publishedts = 1001; type=int; len=10

[stored]
tag =
authorid =
noteid =
threadid =
replyto =
notebook =
published =
`
	if err := os.WriteFile(filepath.Join(s.ConfDir, "fields"), []byte(fields), 0o644); err != nil {
		return err
	}
	mimeconf := fmt.Sprintf(`[index]
text/markdown = exec python3 %s ; mimetype=text/html
`, handlerPath)
	return os.WriteFile(filepath.Join(s.ConfDir, "mimeconf"), []byte(mimeconf), 0o644)
}

// Index runs one incremental recollindex pass over the projection.
func (s *Sidecar) Index(ctx context.Context) error {
	cmd := exec.CommandContext(ctx, s.IndexBinary, "-c", s.ConfDir)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("recollindex: %w: %s", err, strings.TrimSpace(stderr.String()))
	}
	return nil
}

// Hit is one Recoll result mapped back to a managed note.
type Hit struct {
	DocumentID string
	Title      string
	Abstract   string
}

// Search compiles the parsed query to Recoll syntax and runs recollq.
func (s *Sidecar) Search(ctx context.Context, q query.Query, limit int) ([]Hit, error) {
	expr := CompileQuery(q)
	if strings.TrimSpace(expr) == "" {
		return nil, nil
	}
	if limit <= 0 || limit > 200 {
		limit = 50
	}
	cmd := exec.CommandContext(ctx, s.QueryBinary, "-c", s.ConfDir, "-F", "url title abstract", "-n", "0-"+strconv.Itoa(limit), expr)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return nil, fmt.Errorf("recollq: %w: %s", err, strings.TrimSpace(stderr.String()))
	}
	return parseResults(stdout.String()), nil
}

// parseResults reads recollq -F output: header lines followed by one result
// per line of space-separated base64-encoded field values. Lines that do not
// decode are skipped (query echo, result counts).
func parseResults(output string) []Hit {
	hits := []Hit{}
	for _, line := range strings.Split(output, "\n") {
		fields := strings.Fields(line)
		if len(fields) < 1 {
			continue
		}
		decoded := make([]string, 0, len(fields))
		ok := true
		for _, field := range fields {
			raw, err := base64.StdEncoding.DecodeString(field)
			if err != nil {
				ok = false
				break
			}
			decoded = append(decoded, string(raw))
		}
		if !ok || len(decoded) == 0 {
			continue
		}
		id := documentIDFromURL(decoded[0])
		if id == "" {
			continue
		}
		hit := Hit{DocumentID: id}
		if len(decoded) > 1 {
			hit.Title = decoded[1]
		}
		if len(decoded) > 2 {
			hit.Abstract = decoded[2]
		}
		hits = append(hits, hit)
	}
	return hits
}

// documentIDFromURL recovers the document ID from a projection file URL
// (file:///.../notes/<document_id>.md).
func documentIDFromURL(url string) string {
	base := filepath.Base(strings.TrimPrefix(url, "file://"))
	if !strings.HasSuffix(base, ".md") {
		return ""
	}
	return strings.TrimSuffix(base, ".md")
}

// CompileQuery renders the parsed user query in Recoll query syntax
// (SEARCH_QUERY_LANGUAGE.md). Trash queries return "" — trashed notes are
// never projected, so Recoll cannot serve them. notebook: filters compile to
// the projected notebook field (direct name match; SQL-side filtering remains
// authoritative for subtree semantics).
func CompileQuery(q query.Query) string {
	if q.Trashed {
		return ""
	}
	parts := []string{}
	quote := func(v string) string { return `"` + strings.ReplaceAll(v, `"`, ` `) + `"` }
	for _, term := range q.Terms {
		if term.Phrase {
			parts = append(parts, quote(term.Text))
		} else {
			parts = append(parts, term.Text)
		}
	}
	for _, term := range q.Title {
		parts = append(parts, "title:"+quote(term.Text))
	}
	for _, name := range q.Notebooks {
		parts = append(parts, "notebook:"+quote(name))
	}
	for _, tag := range q.Tags {
		parts = append(parts, "tag:"+quote(tag))
	}
	for _, author := range q.Authors {
		parts = append(parts, "author:"+quote(author))
	}
	for _, authorID := range q.AuthorIDs {
		parts = append(parts, "authorid:"+quote(authorID))
	}
	switch {
	case q.Since > 0 && q.Until > 0:
		parts = append(parts, fmt.Sprintf("publishedts:%d..%d", q.Since, q.Until))
	case q.Since > 0:
		parts = append(parts, fmt.Sprintf("publishedts:%d..", q.Since))
	case q.Until > 0:
		parts = append(parts, fmt.Sprintf("publishedts:..%d", q.Until))
	}
	return strings.Join(parts, " ")
}
