#include "sqlite3.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
static void fail(sqlite3 *d,int r,const char *w){if(r!=SQLITE_OK&&r!=SQLITE_DONE&&r!=SQLITE_ROW){fprintf(stderr,"%s: %s\n",w,d?sqlite3_errmsg(d):"open failed");exit(1);}}
static void ex(sqlite3*d,const char*s){fail(d,sqlite3_exec(d,s,0,0,0),s);}
static int num(sqlite3*d,const char*s){sqlite3_stmt*q=0;fail(d,sqlite3_prepare_v2(d,s,-1,&q,0),s);fail(d,sqlite3_step(q),s);int n=sqlite3_column_int(q,0);sqlite3_finalize(q);return n;}
static const char*txt(sqlite3*d,const char*s){static char b[256];sqlite3_stmt*q=0;fail(d,sqlite3_prepare_v2(d,s,-1,&q,0),s);fail(d,sqlite3_step(q),s);const unsigned char*v=sqlite3_column_text(q,0);snprintf(b,sizeof b,"%s",v?(const char*)v:"");sqlite3_finalize(q);return b;}
static void features(sqlite3*d){(void)d;const char*r[]={"THREADSAFE=1","ENABLE_FTS5","DQS=0","OMIT_LOAD_EXTENSION","SECURE_DELETE","USE_URI"};for(size_t i=0;i<6;i++)if(!sqlite3_compileoption_used(r[i])){fprintf(stderr,"missing compile option %s\n",r[i]);exit(1);}}
static sqlite3*open_db(const char*p){sqlite3*d=0;fail(d,sqlite3_open_v2(p,&d,SQLITE_OPEN_READWRITE|SQLITE_OPEN_CREATE|SQLITE_OPEN_FULLMUTEX,0),"open");return d;}
static void verify(sqlite3*d){if(strcmp(txt(d,"PRAGMA integrity_check"),"ok")||strcmp(txt(d,"PRAGMA journal_mode"),"wal"))exit(1);if(num(d,"SELECT count(*) FROM notes")!=1001)exit(1);if(num(d,"SELECT count(*) FROM notes WHERE id=1001 AND title='Modernc round-trip' AND body='written by the modernc candidate' AND json_extract(metadata,'$.source')='modernc'")!=1)exit(1);printf("{\"candidate\":\"amalgamation\",\"mode\":\"verify\",\"sqlite\":\"%s\",\"notes\":1001,\"integrity\":\"ok\",\"journal_mode\":\"wal\",\"modernc_row\":true}\n",sqlite3_libversion());}
static void run_workload(sqlite3*d){clock_t st=clock();ex(d,"PRAGMA journal_mode=WAL;PRAGMA synchronous=NORMAL;PRAGMA busy_timeout=5000;CREATE TABLE IF NOT EXISTS notes(id INTEGER PRIMARY KEY,title TEXT NOT NULL,body TEXT NOT NULL,metadata TEXT NOT NULL,updated_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS revisions(note_id INTEGER NOT NULL,revision INTEGER NOT NULL,body TEXT NOT NULL,PRIMARY KEY(note_id,revision));CREATE TABLE IF NOT EXISTS tags(note_id INTEGER NOT NULL,tag TEXT NOT NULL,PRIMARY KEY(note_id,tag));CREATE VIRTUAL TABLE IF NOT EXISTS notes_fts USING fts5(title,body,content='notes',content_rowid='id');");ex(d,"BEGIN IMMEDIATE");sqlite3_stmt*q=0;fail(d,sqlite3_prepare_v2(d,"INSERT OR REPLACE INTO notes VALUES(?,?,?,?,?)",-1,&q,0),"prepare");for(int i=1;i<=1000;i++){char a[64],b[160],m[160];snprintf(a,sizeof a,"Notebook note %04d",i);snprintf(b,sizeof b,"notrios synthetic body for note %04d with searchable evidence",i);snprintf(m,sizeof m,"{\"source\":\"synthetic\",\"rank\":%d}",i);sqlite3_bind_int(q,1,i);sqlite3_bind_text(q,2,a,-1,SQLITE_TRANSIENT);sqlite3_bind_text(q,3,b,-1,SQLITE_TRANSIENT);sqlite3_bind_text(q,4,m,-1,SQLITE_TRANSIENT);sqlite3_bind_int(q,5,i);fail(d,sqlite3_step(q),"insert");sqlite3_reset(q);sqlite3_clear_bindings(q);}sqlite3_finalize(q);ex(d,"COMMIT");ex(d,"INSERT INTO notes_fts(notes_fts) VALUES('rebuild');INSERT OR REPLACE INTO revisions VALUES(1,1,'initial body');INSERT OR REPLACE INTO tags VALUES(1,'synthetic');");int f=num(d,"SELECT count(*) FROM notes_fts WHERE notes_fts MATCH 'searchable'");char j[32],w[32],i[32];snprintf(j,sizeof j,"%s",txt(d,"SELECT json_extract(metadata,'$.source') FROM notes WHERE id=1"));snprintf(w,sizeof w,"%s",txt(d,"PRAGMA journal_mode"));snprintf(i,sizeof i,"%s",txt(d,"PRAGMA integrity_check"));features(d);if(f!=1000||strcmp(j,"synthetic")||strcmp(w,"wal")||strcmp(i,"ok"))exit(1);ex(d,"PRAGMA wal_checkpoint(TRUNCATE);");printf("{\"candidate\":\"amalgamation\",\"mode\":\"run\",\"sqlite\":\"%s\",\"notes\":1000,\"fts_matches\":%d,\"json_source\":\"%s\",\"journal_mode\":\"%s\",\"integrity\":\"%s\",\"compile_options\":\"THREADSAFE=1,ENABLE_FTS5,DQS=0,OMIT_LOAD_EXTENSION,SECURE_DELETE,USE_URI\",\"elapsed_ms\":%ld}\n",sqlite3_libversion(),f,j,w,i,(long)(1000.0*(clock()-st)/CLOCKS_PER_SEC));}
int main(int n,char**v){if(n!=3||(strcmp(v[1],"run")&&strcmp(v[1],"verify")))return 2;sqlite3*d=open_db(v[2]);if(!strcmp(v[1],"run"))run_workload(d);else verify(d);sqlite3_close(d);return 0;}
