const moduleName = process.env.PLAYWRIGHT_MODULE || 'playwright';
const { chromium } = await import(moduleName);
const base = process.env.G18G_BASE_URL || 'http://127.0.0.1:18618/notrios/';
const shotDir = process.env.G18G_SCREENSHOT_DIR;
const routes = ['index.html','installation.html','service.html','cli.html','query-language.html','selection-planning.html','archive-v2.html','stable-links.html','publishing.html','gui.html','import-export.html','operations.html','api/rest.html','api/mcp.html','troubleshooting.html'];
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/usr/bin/google-chrome', headless: true, args: ['--no-sandbox'] });
const problems = [], external = new Set(), csp = [];
function watch(page, label) { page.on('request', r => external.add(r.url())); page.on('console', m => { if (['error','warning'].includes(m.type())) problems.push(`${label}: ${m.type()}: ${m.text()}`); }); page.on('pageerror', e => problems.push(`${label}: pageerror: ${e.message}`)); page.on('response', r => { if (r.status() >= 400) problems.push(`${label}: HTTP ${r.status()} ${r.url()}`); }); page.on('requestfailed', r => problems.push(`${label}: failed ${r.url()}`)); }
async function prepare(page) { await page.addInitScript(() => { window.__g18gCsp = []; document.addEventListener('securitypolicyviolation', e => window.__g18gCsp.push(`${e.blockedURI}:${e.violatedDirective}`)); }); }
async function contrast(page) { return page.locator('main p').first().evaluate(element => { const rgb = v => { const c = document.createElement('canvas').getContext('2d'); c.fillStyle = v; c.fillRect(0,0,1,1); return [...c.getImageData(0,0,1,1).data].slice(0,3).map(x => { x/=255; return x <= .04045 ? x/12.92 : ((x+.055)/1.055)**2.4; }); }; const lum = x => .2126*x[0]+.7152*x[1]+.0722*x[2]; let n=element,b=[0,0,0,1]; while(n && getComputedStyle(n).backgroundColor === 'rgba(0, 0, 0, 0)') n=n.parentElement; if(n) b=rgb(getComputedStyle(n).backgroundColor); const f=rgb(getComputedStyle(element).color), a=lum(f), z=lum(b); return (Math.max(a,z)+.05)/(Math.min(a,z)+.05); }); }
async function run() {
  const desktop = await browser.newPage({ viewport: { width: 1440, height: 960 } }); await prepare(desktop); watch(desktop, 'desktop');
  await desktop.goto(`${base}index.html`, { waitUntil: 'networkidle' });
  if (!/Notrios documentation/i.test(await desktop.title())) throw Error(`unexpected title: ${await desktop.title()}`);
  if (desktop.url() !== `${base}index.html`) throw Error(`unexpected landing URL: ${desktop.url()}`);
  if (!await desktop.locator('main').isVisible()) throw Error('main is not visible');
  if (await desktop.locator('h1').count() < 1) throw Error('semantic heading rendering missing');
  if (await desktop.locator('nav,main,header,footer').count() < 3) throw Error('landmarks missing');
  if (await desktop.locator('a,button,input').evaluateAll(xs => xs.some(x => !x.getAttribute('aria-label') && x.tagName === 'BUTTON' && !x.textContent.trim()))) throw Error('unlabelled control');
  for (const route of routes) { const r = await desktop.request.get(`${base}${route}`); if (!r.ok()) throw Error(`${route} returned ${r.status()}`); }
  await desktop.goto(`${base}cli.html`, { waitUntil: 'networkidle' }); if (await desktop.locator('pre code').count() < 1) throw Error('semantic code rendering missing');
  await desktop.goto(`${base}service.html`, { waitUntil: 'networkidle' }); if (await desktop.locator('table').count() < 1) throw Error('semantic table rendering missing');
  await desktop.goto(`${base}index.html`, { waitUntil: 'networkidle' });
  await desktop.keyboard.press('Tab'); if (!await desktop.locator(':focus').count()) throw Error('keyboard focus missing');
  const theme = desktop.locator('[data-ledger-theme-button]'); const ratios = {}; if (await theme.count()) { for (const value of ['light','dark','contrast']) { await theme.click(); const choice = desktop.locator(`[data-theme-value="${value}"]`); if (await choice.count()) await choice.click(); const ratio = await contrast(desktop); if (ratio < 4.5) throw Error(`${value} contrast ${ratio}`); ratios[value] = Number(ratio.toFixed(2)); } }
  await desktop.goto(`${base}search/`, { waitUntil: 'networkidle' }); const input = desktop.locator('[data-ledger-search-input]'); if (!await input.count()) throw Error('Pagefind search input missing'); await input.fill('Argon2id'); await desktop.locator('[data-ledger-search-form]').evaluate(f => f.requestSubmit()); await desktop.locator('[data-ledger-search-results] a').first().waitFor(); const href = await desktop.locator('[data-ledger-search-results] a').first().getAttribute('href'); if (!href?.startsWith('/notrios/')) throw Error(`search escaped base: ${href}`);
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 } }); await prepare(mobile); watch(mobile, 'mobile'); await mobile.goto(`${base}index.html`, { waitUntil: 'networkidle' }); const drawer = mobile.locator('[data-ledger-drawer-toggle]'); const box = await drawer.boundingBox(); if (!box || box.width < 44 || box.height < 44) throw Error('drawer target below 44px'); await drawer.click(); if ((await drawer.getAttribute('aria-expanded')) !== 'true') throw Error('drawer did not open'); await mobile.keyboard.press('Escape'); if ((await drawer.getAttribute('aria-expanded')) !== 'false') throw Error('Escape did not close drawer'); const overflow = await mobile.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth); if (overflow > 1) throw Error(`mobile overflow ${overflow}px`);
  for (const p of [desktop,mobile]) { if (await p.locator('#webpack-dev-server-client-overlay, vite-error-overlay, [data-nextjs-dialog], [data-testid="error-overlay"]').count()) throw Error('framework error overlay present'); }
  if (shotDir) { await desktop.screenshot({ path: `${shotDir}/g18g-desktop.png` }); await mobile.screenshot({ path: `${shotDir}/g18g-mobile.png` }); }
  const origin = new URL(base).origin; const bad = [...external].filter(u => !u.startsWith(origin) && !u.startsWith('data:')); const policy = [...(await desktop.evaluate(() => window.__g18gCsp || [])), ...(await mobile.evaluate(() => window.__g18gCsp || []))]; if (bad.length) throw Error(`external requests: ${bad.join(', ')}`); if (problems.length || policy.length) throw Error(`browser problems: ${[...problems, ...policy].join(' | ')}`);
  console.log(JSON.stringify({ routes: routes.length, title: await desktop.title(), known_query: 'Argon2id', theme_contrast_ratios: ratios, mobile_target: box, mobile_overflow_px: overflow, external_requests: bad, csp_violations: policy.length, problems: problems.length, screenshots: shotDir || null }, null, 2));
}
try { await run(); } finally { await browser.close(); }
